# Generated by Django 4.2.6 on 2023-11-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
