# Generated by Django 4.2.6 on 2023-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_register_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_inversion', models.IntegerField(max_length=50)),
                ('precio_venta', models.IntegerField(max_length=50)),
            ],
        ),
    ]
