# Generated by Django 4.2.6 on 2023-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_registro_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_producto',
            name='precio_inversion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro_producto',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
