# Generated by Django 4.2.6 on 2023-11-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_registro_producto_precio_inversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=50)),
                ('producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_inversion', models.IntegerField(max_length=50)),
                ('precio_venta', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
        migrations.DeleteModel(
            name='Registro_Producto',
        ),
    ]
