# Generated by Django 4.2.6 on 2023-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_register_productos_delete_register_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_productos',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register_productos',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='register_productos',
            name='precio_inversion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register_productos',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
