# Generated by Django 4.2.6 on 2023-11-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_register_productos_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_productos',
            name='foto',
            field=models.ImageField(default='animales/perro.png', upload_to='animales/'),
        ),
    ]
