# Generated by Django 4.2.6 on 2023-12-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_productos',
            name='img',
            field=models.ImageField(default='animales/perro.png', upload_to='animales/'),
        ),
        migrations.AddField(
            model_name='register_productos',
            name='img1',
            field=models.ImageField(default='animales/perro.png', upload_to='animales/'),
        ),
    ]
