# Generated by Django 4.2.6 on 2023-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_register_productos_img_register_productos_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_productos',
            name='foto',
            field=models.ImageField(upload_to='animales/'),
        ),
        migrations.AlterField(
            model_name='register_productos',
            name='img',
            field=models.ImageField(upload_to='animales/'),
        ),
        migrations.AlterField(
            model_name='register_productos',
            name='img1',
            field=models.ImageField(upload_to='animales/'),
        ),
    ]
