# Generated by Django 4.2.6 on 2023-12-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='contraseña',
            new_name='cantidad1',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='correo_electro',
            new_name='producto1',
        ),
    ]
