# Generated by Django 4.2.6 on 2023-12-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_contraseña_login_cantidad1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='type',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='cantidad1',
            field=models.IntegerField(),
        ),
    ]
