# Generated by Django 4.2.6 on 2023-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_login_type_alter_login_cantidad1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='producto1',
            new_name='contraseña',
        ),
        migrations.RemoveField(
            model_name='login',
            name='type',
        ),
        migrations.AlterField(
            model_name='login',
            name='cantidad1',
            field=models.CharField(max_length=50),
        ),
    ]
