# Generated by Django 4.2.6 on 2023-12-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_delete_login_imagenes_cantidad1_imagenes_producto1'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='descripcion1',
            field=models.CharField(default=14, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='precio_inversion1',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagenes',
            name='precio_venta1',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='cantidad1',
            field=models.IntegerField(),
        ),
    ]
