# Generated by Django 4.2.6 on 2023-12-08 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_imagenes_descripcion1_imagenes_precio_inversion1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='cantidad1',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='descripcion1',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='precio_inversion1',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='precio_venta1',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='producto1',
        ),
    ]
