# Generated by Django 4.2.6 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_imagenes_description_imagenes_price_inversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_productos',
            old_name='foto',
            new_name='img',
        ),
        migrations.AddField(
            model_name='register_productos',
            name='img1',
            field=models.ImageField(default=12, upload_to='animales/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_productos',
            name='img2',
            field=models.ImageField(default=12, upload_to='animales/'),
            preserve_default=False,
        ),
    ]
