# Generated by Django 4.2.6 on 2023-12-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_register_productos_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_productos',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='register_productos',
            name='img2',
        ),
    ]
