# Generated by Django 4.2.6 on 2023-12-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_register_productos_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_productos',
            name='img1',
            field=models.ImageField(default='animales/perro.png', upload_to='animales/'),
        ),
        migrations.AddField(
            model_name='register_productos',
            name='img2',
            field=models.ImageField(default='animales/perro.png', upload_to='animales/'),
        ),
    ]
